# Generated by Django 6.0.6 on 2026-06-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('jugador', models.CharField(choices=[('Amateur', 'Amateur'), ('Semi-profesional', 'Semi-profesional'), ('Profesional', 'Profesional')], max_length=50)),
                ('cancha', models.CharField(choices=[('Fútbol 5', 'Fútbol 5'), ('Fútbol 7', 'Fútbol 7'), ('Fútbol 11', 'Fútbol 11')], max_length=50)),
                ('estrellas', models.IntegerField(default=0)),
                ('texto', models.TextField()),
                ('archivada', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
