# Generated by Django 4.1.13 on 2026-07-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_alter_resena_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
