# Generated by Django 6.0.7 on 2026-08-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0003_resena_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resena',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
