# Generated by Django 4.2.19 on 2026-08-09 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alter_reserva_estado_alter_reserva_id'),
        ('contacto', '0004_alter_resena_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='reserva',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resena', to='reservas.reserva'),
        ),
        migrations.AlterField(
            model_name='resena',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
