# Generated by Django 4.2.19 on 2026-09-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0007_mensajecontacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajecontacto',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='resena',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
