# Generated by Django 6.1 on 2026-08-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('horas', models.JSONField(blank=True, default=list)),
                ('cancha', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('numero_factura', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_pago', models.CharField(blank=True, choices=[('completo', 'Pago completo'), ('abono', 'Abono (50%)')], max_length=20, null=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pasarela', models.CharField(blank=True, choices=[('simulado', 'Simulado'), ('mercadopago', 'Mercado Pago'), ('stripe', 'Stripe')], max_length=20, null=True)),
                ('referencia_pago', models.CharField(blank=True, max_length=120, null=True)),
                ('referencia_pago_confirmado', models.CharField(blank=True, max_length=120, null=True)),
                ('pago_verificado', models.BooleanField(default=False)),
            ],
        ),
    ]
