# Generated by Django 6.0.7 on 2026-07-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Fútbol 5', 'Fútbol 5'), ('Fútbol 7', 'Fútbol 7'), ('Fútbol 11', 'Fútbol 11')], default='Fútbol 5', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='canchas/')),
                ('disponible', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cancha',
                'verbose_name_plural': 'Canchas',
                'ordering': ['-creada'],
            },
        ),
    ]
