# Generated by Django 4.2.19 on 2026-08-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_canchas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='precio',
            field=models.PositiveIntegerField(help_text='Valor por hora en pesos colombianos (COP), sin decimales'),
        ),
    ]
