# Generated by Django 4.2.19 on 2026-09-09 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_canchas', '0003_sede_cancha_sede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancha',
            name='sede',
        ),
        migrations.AlterField(
            model_name='cancha',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
