# Generated by Django 4.2.19 on 2026-09-14 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_canchas', '0004_remove_cancha_sede_alter_cancha_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='sede',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='canchas', to='gestion_canchas.sede'),
            preserve_default=False,
        ),
    ]
