# Generated by Django 4.1.13 on 2026-07-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_id_auditoriarol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='avatar_icono',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles/'),
        ),
    ]
