# Generated by Django 4.2.19 on 2026-09-20 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0005_usuario_avatar_icono_usuario_foto'),
        ('gestion_canchas', '0005_cancha_sede'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(max_length=100)),
                ('horario', models.CharField(max_length=100)),
                ('aceptado', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('aceptado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retos_aceptados', to='usuarios.usuario')),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retos', to='gestion_canchas.cancha')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retos_creados', to='usuarios.usuario')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='PublicacionMuro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_mostrar', models.CharField(max_length=100)),
                ('texto', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_muro', to='usuarios.usuario')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='PartidoAbierto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_texto', models.CharField(max_length=100)),
                ('jugadores_faltan', models.PositiveIntegerField(default=1)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_abiertos', to='gestion_canchas.cancha')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidos_creados', to='usuarios.usuario')),
                ('participantes', models.ManyToManyField(blank=True, related_name='partidos_unidos', to='usuarios.usuario')),
            ],
            options={
                'ordering': ['fecha', '-creado'],
            },
        ),
    ]
