# Generated by Django 4.2.19 on 2026-09-20 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_avatar_icono_usuario_foto'),
        ('reservas', '0011_reserva_cancelada_por_reserva_fecha_cancelacion_and_more'),
        ('comunidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidoabierto',
            name='cobra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partidoabierto',
            name='reserva',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partido_abierto', to='reservas.reserva'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partidoabierto',
            name='valor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reto',
            name='cobra',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reto',
            name='reserva',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reto', to='reservas.reserva'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reto',
            name='valor',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.PositiveIntegerField()),
                ('pagado', models.BooleanField(default=False)),
                ('mp_preference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('partido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='comunidad.partidoabierto')),
                ('reto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='comunidad.reto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aportes', to='usuarios.usuario')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
