# Generated by Django 4.1.13 on 2026-07-29 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_alter_cancha_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancha',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='AuditoriaCancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_nuevo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('disponible_anterior', models.BooleanField(blank=True, null=True)),
                ('disponible_nuevo', models.BooleanField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='canchas.cancha')),
            ],
        ),
    ]
