# Generated by Django 4.2.19 on 2026-08-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alter_reserva_estado_alter_reserva_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='horas',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
