# Generated by Django 4.2.19 on 2026-08-12 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_reserva_horas'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='saldo_pendiente',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo_pago',
            field=models.CharField(blank=True, choices=[('completo', 'Pago completo'), ('abono', 'Abono (50%)')], max_length=20, null=True),
        ),
    ]
