# Generated by Django 4.2.19 on 2026-08-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_alter_reserva_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='mp_preference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
