# Generated by Django 4.2.19 on 2026-09-16 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0010_reserva_mp_preference_id_alter_reserva_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cancelada_por',
            field=models.CharField(blank=True, choices=[('usuario', 'Usuario'), ('admin', 'Administrador')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, choices=[('clima', 'Mal clima / cancha en mal estado'), ('equipo', 'No se completó el equipo'), ('horario', 'Se me cruzó con otro compromiso'), ('error', 'Me equivoqué al reservar (fecha, hora o cancha)'), ('salud', 'Motivos de salud o lesión'), ('precio', 'Encontré otra opción / tema de precio'), ('otro', 'Otro motivo')], max_length=20, null=True, verbose_name='Motivo de cancelación'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='motivo_detalle',
            field=models.TextField(blank=True, null=True, verbose_name='Detalle del motivo'),
        ),
    ]
